// ? Products

export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

// ? Product Details

export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST';
export const PRODUCT_DETAIL_SUCCESS = 'PRODUCT_DETAIL_SUCCESS';
export const PRODUCT_DETAIL_FAIL = 'PRODUCT_DETAIL_FAIL';

// ? CART ITEMS

export const ADD_TO_CART = 'ADD_TO_CART';
export const EMPTY_CART = 'EMPTY_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const INCREASE_CART_ITEM = 'INCREASE_CART_ITEM';
export const DECREASE_CART_ITEM = 'DECREASE_CART_ITEM';
export const TOGGLE_DROPDOWN = 'TOGGLE_DROPDOWN';
export const INCREASE_CART_QUANTITY = 'INCREASE_CART_QUANTITY';
export const DECREASE_CART_QUANTITY = ' DECREASE_CART_QUANTITY';
export const TOGGLE_PROFILE_DROPDOWN = ' TOGGLE_PROFILE_DROPDOWN';

// ? User

export const USER_LOGIN_REQUEST = ' USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = ' USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = ' USER_LOGIN_FAIL';
export const USER_LOGOUT = ' USER_LOGIN_LOGOUT';

// ? REGISTER USER

export const USER_REGISTER_REQUEST = ' USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = ' USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = ' USER_REGISTER_FAIL';

// ? GET USER PROFILE

export const USER_PROFILE_DETAILS_REQUEST = ' USER_PROFILE_DETAILS_REQUEST';
export const USER_PROFILE_DETAILS_SUCCESS = ' USER_PROFILE_DETAILS_SUCCESS';
export const USER_PROFILE_DETAILS_FAIL = ' USER_PROFILE_DETAILS_FAIL';
export const USER_PROFILE_DETAILS_CLEAR = ' USER_PROFILE_DETAILS_CLEAR';

// ? UPDATE USER

export const USER_UPDATE_PROFILE_REQUEST = ' USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = ' USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = ' USER_UPDATE_PROFILE_FAIL';

// ? ADDED SHIPPING INFO
export const ADDED_SHIPPING_ADRESS = ' ADDED_SHIPPING_ADRESS';
export const ADDED_SHIPPING_METHOD = ' ADDED_SHIPPING_METHOD';
export const ADDED_PAYMENT_METHOD = ' ADDED_PAYMENT_METHOD';

//! =================================================================

// ? ADDED ORDER
export const ADDED_ORDER_REQUEST = ' ADDED_ORDER_REQUEST';
export const ADDED_ORDER_SUCCESS = ' ADDED_ORDER_SUCCESS';
export const ADDED_ORDER_FAIL = ' ADDED_ORDER_FAIL';

// ? GET ORDER DETAILS
export const ORDER_DETAILS_REQUEST = ' ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = ' ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = ' ORDER_DETAILS_FAIL';

// ? PROCEED TO PAYMENT
export const PAYMENT_REQUEST = ' PAYMENT_REQUEST';
export const PAYMENT_SUCCESS = ' PAYMENT_SUCCESS';
export const PAYMENT_FAIL = ' PAYMENT_FAIL';
