// ? Products

export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

// ? Product Details

export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST';
export const PRODUCT_DETAIL_SUCCESS = 'PRODUCT_DETAIL_SUCCESS';
export const PRODUCT_DETAIL_FAIL = 'PRODUCT_DETAIL_FAIL';

// ? CART ITEMS

export const ADD_TO_CART = 'ADD_TO_CART';
export const EMPTY_CART = 'EMPTY_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const INCREASE_CART_ITEM = 'INCREASE_CART_ITEM';
export const DECREASE_CART_ITEM = 'DECREASE_CART_ITEM';
export const TOGGLE_DROPDOWN = 'TOGGLE_DROPDOWN';
export const INCREASE_CART_QUANTITY = 'INCREASE_CART_QUANTITY';
export const DECREASE_CART_QUANTITY = ' DECREASE_CART_QUANTITY';
export const TOGGLE_PROFILE_DROPDOWN = ' TOGGLE_PROFILE_DROPDOWN';

// ? User

export const USER_LOGIN_REQUEST = ' USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = ' USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = ' USER_LOGIN_FAIL';
export const USER_LOGOUT = ' USER_LOGIN_LOGOUT';

// ? REGISTER USER

export const USER_REGISTER_REQUEST = ' USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = ' USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = ' USER_REGISTER_FAIL';

// ? GET USER PROFILE

export const USER_PROFILE_DETAILS_REQUEST = ' USER_PROFILE_DETAILS_REQUEST';
export const USER_PROFILE_DETAILS_SUCCESS = ' USER_PROFILE_DETAILS_SUCCESS';
export const USER_PROFILE_DETAILS_FAIL = ' USER_PROFILE_DETAILS_FAIL';
export const USER_PROFILE_DETAILS_CLEAR = ' USER_PROFILE_DETAILS_CLEAR';

// ? UPDATE USER

export const USER_UPDATE_PROFILE_REQUEST = ' USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = ' USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = ' USER_UPDATE_PROFILE_FAIL';

// ? ADDED SHIPPING INFO
export const ADDED_SHIPPING_ADRESS = ' ADDED_SHIPPING_ADRESS';
export const ADDED_SHIPPING_METHOD = ' ADDED_SHIPPING_METHOD';
export const ADDED_PAYMENT_METHOD = ' ADDED_PAYMENT_METHOD';

//! =================================================================

// ? ADDED ORDER
export const ADDED_ORDER_REQUEST = ' ADDED_ORDER_REQUEST';
export const ADDED_ORDER_SUCCESS = ' ADDED_ORDER_SUCCESS';
export const ADDED_ORDER_FAIL = ' ADDED_ORDER_FAIL';
export const ADDED_ORDER_RESET = ' ADDED_ORDER_RESET';

// ? GET ORDER DETAILS
export const ORDER_DETAILS_REQUEST = ' ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = ' ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = ' ORDER_DETAILS_FAIL';
export const ORDER_DETAILS_RESET = ' ORDER_DETAILS_RESET';
// ? GET ORDERS DETAILS
export const ORDERS_DETAILS_REQUEST = ' ORDERS_DETAILS_REQUEST';
export const ORDERS_DETAILS_SUCCESS = ' ORDERS_DETAILS_SUCCESS';
export const ORDERS_DETAILS_FAIL = ' ORDERS_DETAILS_FAIL';
export const ORDERS_DETAILS_RESET = ' ORDERS_DETAILS_RESET';

// ? PROCEED TO PAYMENT
export const PAYMENT_REQUEST = ' PAYMENT_REQUEST';
export const PAYMENT_SUCCESS = ' PAYMENT_SUCCESS';
export const PAYMENT_FAIL = ' PAYMENT_FAIL';

// ? UPDATE  PAYMENT STATUS FOR STRIPE
export const PAYMENT_STRIPE_UPDATE_REQUEST = ' PAYMENT_STRIPE_UPDATE_REQUEST';
export const PAYMENT_STRIPE_UPDATE_SUCCESS = ' PAYMENT_STRIPE_UPDATE_SUCCESS';
export const PAYMENT_STRIPE_UPDATE_FAIL = ' PAYMENT_STRIPE_UPDATE_FAIL';
export const PAYMENT_STRIPE_RESET = ' PAYMENT_STRIPE_RESET';

// ? UPDATE  PAYMENT STATUS FOR PAYPAL
export const PAYMENT_PAYPAL_UPDATE_REQUEST = ' PAYMENT_PAYPAL_UPDATE_REQUEST';
export const PAYMENT_PAYPAL_UPDATE_SUCCESS = ' PAYMENT_PAYPAL_UPDATE_SUCCESS';
export const PAYMENT_PAYPAL_UPDATE_FAIL = ' PAYMENT_PAYPAL_UPDATE_FAIL';
export const PAYMENT_PAYPAL_RESET = ' PAYMENT_PAYPAL_RESET';

//! ====================== ADMIN ==================================

// ? GET USERS LIST
export const USERS_LIST_REQUEST = ' USERS_LIST_REQUEST';
export const USERS_LIST_SUCCESS = ' USERS_LIST_SUCCESS';
export const USERS_LIST_FAIL = ' USERS_LIST_FAIL';
export const USERS_LIST_RESET = ' USERS_LIST_RESET';

// ? DELETE USER
export const REMOVE_USER_REQUEST = ' REMOVE_USER_REQUEST';
export const REMOVE_USER_SUCCESS = ' REMOVE_USER_SUCCESS';
export const REMOVE_USER_FAIL = ' REMOVE_USER_FAIL';

// SHOW and Hide Modal
export const SHOW_MODAL = ' SHOW_MODAL';
export const HIDE_MODAL = ' HIDE_MODAL';
